# Generated by Django 3.1.7 on 2021-02-25 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topit', '0002_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='user',
            new_name='name',
        ),
    ]
